group: io.kestra.plugin.shopify.products
name: "products"
title: "Shopify Order"
description: "This sub-group of plugins contains tasks to interact with Shopify Products."
body: ""
videos: []
createdBy: "Kestra Core Team"
managedBy: "Kestra Core Team"
